jetty:
  context: /
  connectors:
    - port: 8182
      type: https2

jdbc:
  angel-derby-inmemory-test:
    url: jdbc:derby:memory:onCourse;create=true
    driverClassName: org.apache.derby.jdbc.EmbeddedDriver
    initialSize: 1
    rollbackOnReturn: true
    defaultAutoCommit: false

cayenne:
  datasource: angel-derby-inmemory-test
  configs:
    - cayenne/cayenne-Angel.xml
