name: send application decision
keyCode: ish.script.sendApplicationDecision
body: ish.script.sendApplicationDecision.groovy
enabled: false
triggerType: ENTITY_EVENT
entityClass: Application
entityEventType: CREATE_OR_UPDATE
description: Send an email to the student about whether their application has been offered or rejected
options:
  - name: applicationAcceptedTemplate
    dataType: MESSAGE_TEMPLATE
    value: "ish.email.enrolmentApplicationAccepted"
  - name: applicationRejectedTemplate
    dataType: MESSAGE_TEMPLATE
    value: "ish.email.enrolmentApplicationRejected"