name: send application received notification
keyCode: ish.script.sendApplicationReceivedNotification
body: ish.script.sendApplicationReceivedNotification.groovy
enabled: false
triggerType: ENTITY_EVENT
entityClass: Application
entityEventType: CREATE
description: Send an email to the student when their application has been received
options:
  - name: applicationReceivedTemplate
    dataType: MESSAGE_TEMPLATE
    value: "ish.email.enrolmentApplicationReceived"