type: object
properties:
  id:
    type: integer
    format: int64
    required: true
  createCrediNote:
    type: boolean
    required: true
  retainAdministrativeFee:
    type: boolean
    required: true
  feeAmount:
    type: number
    required: true
  feeTaxId:
    type: integer
    format: int64
    required: true
  retainAccountId:
    type: integer
    format: int64
    required: true