name: Enrolment application received
type: email
keyCode: ish.email.enrolmentApplicationReceived
txtTemplate: ish.email.enrolmentApplicationReceived.txt
htmlTemplate: ish.email.enrolmentApplicationReceived.html
subject: Enrolment application received
entityClass: Application
description: An email to the student when their application has been received
options:
  - name: headerKeycode
    dataType: TEXT
    value: ish.email.header
  - name: footerKeycode
    dataType: TEXT
    value: ish.email.footer