name: Enrolment application rejected
type: email
keyCode: ish.email.enrolmentApplicationRejected
txtTemplate: ish.email.enrolmentApplicationRejected.txt
htmlTemplate: ish.email.enrolmentApplicationRejected.html
subject: Your application for ${application.course.name}
entityClass: Application
description: An email about whether their application has been rejected
options:
  - name: headerKeycode
    dataType: TEXT
    value: ish.email.header
  - name: footerKeycode
    dataType: TEXT
    value: ish.email.footer