name: Enrolment application accepted
type: email
keyCode: ish.email.enrolmentApplicationAccepted
txtTemplate: ish.email.enrolmentApplicationAccepted.txt
htmlTemplate: ish.email.enrolmentApplicationAccepted.html
subject: Approval to enrol in ${application.course.name}
entityClass: Application
description: An email about whether their application has been offered
options:
  - name: headerKeycode
    dataType: TEXT
    value: ish.email.header
  - name: footerKeycode
    dataType: TEXT
    value: ish.email.footer